#Application
server:
  port: 8083

spring:
  application:
    name: ride-service

  #PostgreSQL Database
  datasource:
    url: jdbc:postgresql://localhost:5432/uberapp
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ride-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.RideShare.RiderService.Event.RideMatchedEvent

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info